### ISSUE TITLE
Randomly failing UI tests, when upgrading to OC 1.5 (OSOE-483)

### ISSUE THREAD

**Issue by dministro** [Lombiq/UI-Testing-Toolbox#239]
In some cases, the browser navigation results in HTTP 500. In this state, there are no logs under FaliureDump folder, and looks like the web app won't start.

Related:

- https://github.com/Lombiq/UI-Testing-Toolbox/pull/225
- https://github.com/Lombiq/UI-Testing-Toolbox/pull/225#discussion_r1019797990

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-483)

**Comment by dministro** [comment]
After I collected the logs of many failed runs, I found errors only in the `internal-nlog.txt`, like below:
```
...
2022-11-24 20:18:24.4539 Error Failed to add type 'NLog.Web.LayoutRenderers.AspNetRequestConnectionIdLayoutRenderer'. Exception: System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at NLog.Config.Factory`2.RegisterDefinition(String itemName, Type itemDefinition, String assemblyName, String itemNamePrefix)
   at NLog.Config.Factory`2.RegisterType(Type type, String assemblyName, String itemNamePrefix)
   at NLog.Config.Factory`2.ScanTypes(Type[] types, String assemblyName, String itemNamePrefix)
2022-11-24 20:18:24.4540 Error Failed to add type 'NLog.Web.LayoutRenderers.AspNetRequestConnectionIdLayoutRenderer'. Exception: System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at NLog.Config.Factory`2.RegisterDefinition(String itemName, Type itemDefinition, String assemblyName, String itemNamePrefix)
   at NLog.Config.Factory`2.RegisterType(Type type, String assemblyName, String itemNamePrefix)
   at NLog.Config.Factory`2.ScanTypes(Type[] types, String assemblyName, String itemNamePrefix)
2022-11-24 20:18:24.4625 Error Failed to add type 'NLog.Web.LayoutRenderers.AspNetMvcActionRenderer'. Exception: System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at NLog.Config.Factory`2.RegisterDefinition(String itemName, Type itemDefinition, String assemblyName, String itemNamePrefix)
   at NLog.Config.Factory`2.RegisterType(Type type, String assemblyName, String itemNamePrefix)
   at NLog.Config.Factory`2.ScanTypes(Type[] types, String assemblyName, String itemNamePrefix)
...
```
I started from here and added a `lock` around [Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory<TEntryPoint>.CreateHost(IHostBuilder builder)](https://github.com/dotnet/aspnetcore/blob/32e8c8cae5b1a4dd752d0a42a6f8a2813f75f173/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs#L438) in [Lombiq.Tests.UI.Services.OrchardCoreHosting.OrchardApplicationFactory<TStartup>.CreateHost(IHostBuilder builder)](https://github.com/Lombiq/UI-Testing-Toolbox/blob/5aa79f14156869082e3b36b4e7afab1034b0a66f/Lombiq.Tests.UI/Services/OrchardCoreHosting/OrchardApplicationFactory.cs#L54), because the `CreateHost` invokes [Microsoft.Extensions.Hosting.HostFactoryResolver.CreateHost()](https://github.com/dotnet/runtime/blob/5a400c212afdf8e675c9a1d38442e6d2f19f7b74/src/libraries/Microsoft.Extensions.HostFactoryResolver/src/HostFactoryResolver.cs#L220) which starts the web application in a new thread, and finally this can result in exceptions as I found in the `internal-nlog.txt` in case of parallel execution of tests.

After I added the change above, I wasn't faced with the issue again. I ran the tests locally and on GHA without any issues. See: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/307

**Comment by 0liver** [comment]
Great work, Sherlock! 🧐

**Comment by Piedone** [comment]
Fixed by https://github.com/Lombiq/UI-Testing-Toolbox/pull/240.
